### ISSUE TITLE
x11-wm/mutter wayland compatible

### ISSUE THREAD

**Issue by jrevillard** [hhfeuer/Gentoo-Gnome-3.32-X#2]
I know that this is not the goal of this repository but just in case, inspired from the https://github.com/Heather/gentoo-gnome overlay, here is a mutter version wayland compatible.

[mutter-3.32.2-r1.ebuild](https://github.com/hhfeuer/Gentoo-Gnome-3.32-X/files/3462120/mutter-3.32.2-r1.ebuild.txt)

Best,
Jerome

**Comment by hhfeuer** [comment]
The ebuild by itself should be USE="wayland" compatible. It's just not tested and updated dependencies are not included.
